### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by RustamovAzer** [run-x/opta#647]
#### What happened:
`opta apply -c flyte.yaml --auto-approve` returned this error:
```
╷
│ Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
│
│   with module.helmchart.helm_release.local_chart[0],
│   on ../../../.opta/modules/helm_chart/tf_module/main.tf line 18, in resource "helm_release" "local_chart":
│   18: resource "helm_release" "local_chart" {
│
╵
```

#### How to reproduce it (as minimally and precisely as possible):
I followed [this](https://docs.flyte.org/en/latest/deployment/aws/opta.html#deployment-aws-opta) instruction with two changes:
1. I deleted these lines from `env.yaml':
```
  - type: dns
    domain: <domain>
    delegated: false # set to true once ready https://docs.opta.dev/miscellaneous/ingress/
```
2. I changed files `.opta/modules/aws_s3/aws-s3.yaml`, `.opta/modules/aws_s3/tf_module/replication.tf`, `.opta/modules/aws_base/tf_module/log_bucket.tf` to remove public access blocks for s3 buckets. 

#### Environment:
- Opta version (use `opta version`): `v0.24.3`
- Cloud provider (or hardware configuration for local): `AWS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04`
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by bigbitbus** [comment]
Hi @RustamovAzer, can you reconfirm the opta version as being v.0.24.3 (https://github.com/run-x/opta/tree/v0.24.3) released about 6 days ago?

Also, if you can post information about the Kubernetes cluster version (available in the AWS EKS console for example) that would be helpful. Thanks!

**Comment by RustamovAzer** [comment]
Checked `opta version` again: it is indeed `v0.24.3`
Kubernetes cluster version: 1.18

**Comment by juandiegopalomino** [comment]
@RustamovAzer It's an issue with flyte because of this: https://github.com/flyteorg/flyte/blob/master/charts/flyte-core/templates/common/ingress.yaml#L61

By default Opta is using K8s version 1.18 (we are updating this on our next release so this will not happen after that), which does not support this API version. For now, here is what you can do:
1. Destroy your existing cluster and manually update the k8s version in your opta yamls like this
```yaml
.
.
.
  - type: k8s-cluster
    max_nodes: 15
    k8s_version: 1.21
.
.
.
```
2. Pin the flyte version to the not beta like so
```yaml
.
.
.
  - type: helm-chart
    chart: "../../charts/flyte-core" # NOTE: relative path to chart
    namespace: flyte
    timeout: 600
    create_namespace: true
    values_file: "../../charts/flyte-core/values-eks.yaml" # NOTE: relative path to values yaml
    chart_version: "v0.19.1"
.
.
.
```

Let me know if you have any more questions or need help!
