### ISSUE TITLE
Cannot use variables for CPU and Memory Resource Requests / Limits

### ISSUE THREAD

**Issue by edeesis** [run-x/opta#886]
#### What happened:

When using [variables](https://docs.opta.dev/features/variables/) for CPU and memory, we get this error:

```
Opta file validation failed with errors:
  : modules.0: resource_request.cpu: '{vars.cpu}' is not a int.
  : modules.0: resource_request.cpu: '{vars.cpu}' is not a regex match.
  : modules.0: resource_request.memory: '{vars.memory}' is not a int.
  : modules.0: resource_request.memory: '{vars.memory}' is not a regex match.
```

#### What you expected to happen:

The variable replacement for CPU and memory to work as documented similarly to min_containers and max_containers.

#### How to reproduce it (as minimally and precisely as possible):

```
name: app
environments:
  - name: staging
    path: "staging.yml"
    vars:
      min_containers: 1
      max_containers: 1
      cpu: 1000
      memory: 2048
      environment: staging
modules:
  - type: k8s-service
    name: api
    image: AUTO
    resource_request:
      cpu: "{vars.cpu}"
      memory: "{vars.memory}"
    min_containers: "{vars.min_containers}"
    max_containers: "{vars.max_containers}"
```

#### Environment:
- Opta version (use `opta version`): 0.31.0
- Cloud provider (or hardware configuration for local): AWS
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`): Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
