### ISSUE TITLE
Expose Account ID in opta output

### ISSUE THREAD

**Issue by edeesis** [run-x/opta#910]
#### What would you like to be added:

We'd like to use the AWS Account ID as a variable in our Opta YML, particularly for the additional_iam_policies field.

#### Why is this needed:

Without this, we have to copy-paste the account ID across numerous Opta files.

### Extra info (e.g. existing slack convo link):

**Comment by juandiegopalomino** [comment]
huh, it should already be exposed as a variable:
```yaml
name: hello
environments:
  - name: staging
    path: "./aws-live-example.yaml" # the file we created in previous step
modules:
  - type: k8s-service
    name: hello
    image: "kennethreitz/httpbin:latest"
    port:
      http: "80"
    env_vars:
      blah: "{aws.account_id}"
```
but if you also need it in outputs pls see https://github.com/run-x/opta/pull/917 !
